export type { NavigationAccumulate, NavigationLink, NavigationSections } from './types'
export {
  NAVIGATION_SECTIONS,
  NAVIGATION_APPLICATION_SECTION,
  NAVIGATION_AUTHOR_SECTION,
  NAVIGATION_PROJECTS_SECTION,
  NAVIGATION_DEVELOPMENT_SECTION,
  NAVIGATION_SECONDARY_SECTION,
} from './navigation'
